# This is a basic workflow to help you get started with Actions

name: CURL trod.pub

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'trod.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Curl-Trod-Pub-Actions:
    runs-on: ubuntu-latest
    env:
        payload: "{'commit':'${{ github.sha }}'}"
        secret: "${{ secrets.SYNC_DATA_SECRET }}"
    steps:
      - run: |
          key=$(expr ${{ env.payload }} | openssl sha256 -hmac ${{ env.secret }})
          curl -X POST http://trod-app.trod-pub.20234050.cn-hangzhou.fc.devsapp.net/syncdata \
          -H "X-Fc-Invocation-Type: Async" \
          -H "x-hub-signature-256: sha256=${key}" \
          -H "content-type: application/json" \
          -d ${{ env.payload }}
